### ISSUE TITLE
Add Light / Dark Theme selection also on root and home pages

### ISSUE THREAD

**Issue by ncarandini** [MicrosoftDocs/Docs#23]
While I do like the ability to choose the Light / Dark theme (kudos for that!), I miss the ability to change it from the root [Microsoft Docs page](docs.microsoft.com) and home pages of:
- [.NET Core](https://docs.microsoft.com/it-it/dotnet/index)
- [Azure Active Directory Documentation](https://docs.microsoft.com/en-us/active-directory/)
- ...

Can you add the same theme selector found on inner pages (like [Welcome to .NET](https://docs.microsoft.com/en-us/dotnet/articles/welcome) page), maybe at footer level, just right of the the language selection?

Thanks!

**Comment by BryanLa** [comment]
Hi @ncarandini - thanks for the suggestion! This has actually been added to the docs.microsoft.com user voice page, if you'd like to vote it up: https://msdocs.uservoice.com/forums/364242-general-site-feedback?query=theme.

**Comment by mairaw** [comment]
That's a different request @BryanLa, but @ncarandini that user voice site is a good place to provide feedback on the site in general, so feel free to file a new request.

**Comment by BryanLa** [comment]
Hi @mairaw - I think @ncarandini is saying "I'd like the theme selector on all pages (not just hub/landing), so I can control Dark vs. Light, since it currently defaults to Light", whereas the user voice request is saying "I'd like the theme to be Dark everywhere" ie: they're worded differently, but basically asking for the control so they can customize (like the non-hub/landing pages). See also the comment in the user voice request: https://msdocs.uservoice.com/forums/364242-general-site-feedback/suggestions/14999211-komplete-dark-theme.

@ncarandini If this is correct, your vote will add to the 4 that exist already. If not and I'm misunderstanding, by all means please use https://msdocs.uservoice.com/forums/364242-general-site-feedback to submit a new one!

**Comment by ncarandini** [comment]
@mairaw thanks to suggest me to use a better way to ask for enhancements and leave issue creation for real issues. The point here is that this is, IMHO, more an issue than an enhancement request. Let me try to better explain my point of view (and thanks to @BryanLa for trying to do it on my behalf).

### Scenario:
  1. As a reader, I navigate to [.NET Core Guide](https://docs.microsoft.com/en-us/dotnet/articles/core/)
  2. Using the Theme selector, I select the dark theme
  3. Using the Breadcrumb (navigation) link I navigate to the [docs root page](https://docs.microsoft.com/en-us/)

### Result
The root page is retaining my theme chosen in the previous page and is shown using the dark theme.

### Issue
If the page is following a theme, I should be able to switch the theme form that page, but I cannot because no theme selector is present on the UI of the page.

### Workaround
Navigate to a page of the .NET Core Docs, change select the desired theme and go back to the page.

### Recap
To me this is more an issue of inconsistent UI than a feature request. Do you agree with me?

**Comment by BryanLa** [comment]
@ncarandini - yes, completely agree w/you, and thanks for sharing the additional details. If the theme selector control were available on all pages, I believe that would solve this as well. 

Let me run this past the web site/UI team and see if they are aware of this, and if not, whether we can file a bug to fix. We'll get back to you with the response. And thanks again!

**Comment by DuncanmaMSFT** [comment]
@ncarandini @BryanLa we are planning to move the theme control into an option in the header or footer, like you suggest, at some point in the future. Definitely agree it needs to be available on all pages, just below a lot of higher priority items at the moment. We'll come back and update this thread when we make this available. Thanks for the feedback!

**Comment by mairaw** [comment]
I agree with both of you @BryanLa and @ncarandini. But I think that feedback on UserVoice was about the hub always been displayed white no matter your theme selection since @dend indicated that the feature had been implemented already vs. having the selector on the hub which is something that @DuncanmaMSFT's team still needs to implement.

**Comment by ncarandini** [comment]
Thanks all for yours kind replies, and thanks for all the great work you're doing with the docs site. And yes, it's a really minor issue, I just wanted to signal it here.

**Comment by dend** [comment]
Closing in favor of https://github.com/MicrosoftDocs/feedback/issues/245

FYI @ncarandini @mairaw @DuncanmaMSFT
